default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: skydropx_dev

test:
  <<: *default
  database: skydropx_test

production:
  <<: *default
  database: skydropx_prod
  password: <%= ENV['PROMEDIC_DATABASE_PASSWORD'] %>
